#include "GitHubUploader.h"

juce::String GitHubUploader::submit (const DiagnosticData& data, juce::String& errorOut)
{
    if (config_.githubRepo.isEmpty() || config_.githubPAT.isEmpty())
    {
        errorOut = "GitHub configuration is invalid. Please check your .env file.";
        return {};
    }

    auto title = "Diagnostic Report - " + juce::Time::getCurrentTime().toString (true, true, false);
    auto body = formatIssueBody (data);

    auto url = juce::URL ("https://api.github.com/repos/" + config_.githubRepo + "/issues")
                   .withPOSTData ("{\"title\":" + juce::JSON::toString (title)
                                  + ",\"body\":" + juce::JSON::toString (body)
                                  + ",\"labels\":[\"diagnostic-report\",\"automated\"]}");

    int statusCode = 0;

    for (int attempt = 0; attempt < config_.githubAPIRetries; ++attempt)
    {
        auto options = juce::URL::InputStreamOptions (juce::URL::ParameterHandling::inPostData)
                           .withExtraHeaders ("Accept: application/vnd.github+json\r\n"
                                              "Authorization: Bearer " + config_.githubPAT + "\r\n"
                                              "X-GitHub-Api-Version: 2022-11-28\r\n"
                                              "Content-Type: application/json\r\n")
                           .withConnectionTimeoutMs (config_.githubAPITimeout * 1000)
                           .withStatusCode (&statusCode);

        auto stream = url.createInputStream (options);

        if (stream != nullptr)
        {
            auto responseBody = stream->readEntireStreamAsString();

            if (statusCode == 201)
            {
                // Parse issue URL from response
                auto json = juce::JSON::parse (responseBody);
                if (auto* obj = json.getDynamicObject())
                {
                    auto htmlUrl = obj->getProperty ("html_url").toString();
                    if (htmlUrl.isNotEmpty())
                        return htmlUrl;
                }
                errorOut = "Could not parse issue URL from response.";
                return {};
            }
            else if (statusCode == 401 || statusCode == 403)
            {
                errorOut = "GitHub authentication failed. Please check your Personal Access Token.";
                return {};
            }
            else if (statusCode == 429)
            {
                errorOut = "GitHub rate limit exceeded. Please try again later.";
                return {};
            }
            else
            {
                errorOut = "HTTP " + juce::String (statusCode) + ": " + responseBody.substring (0, 200);
                // Retry on server errors
                if (statusCode >= 500 && attempt < config_.githubAPIRetries - 1)
                {
                    juce::Thread::sleep ((attempt + 1) * 2000);
                    continue;
                }
                return {};
            }
        }
        else
        {
            errorOut = "Network error: could not connect to GitHub.";
            if (attempt < config_.githubAPIRetries - 1)
            {
                juce::Thread::sleep ((attempt + 1) * 2000);
                continue;
            }
            return {};
        }
    }

    return {};
}

juce::String GitHubUploader::formatIssueBody (const DiagnosticData& data)
{
    juce::String body;

    if (data.userFeedback.isNotEmpty())
    {
        body << "## User Feedback\n\n" << data.userFeedback << "\n\n---\n\n";
    }

    body << data.systemInfo << "\n\n---\n\n";
    body << data.pluginStatus << "\n\n---\n\n";
    body << data.crashLogs << "\n\n---\n\n";
    body << data.pluginValidation << "\n\n---\n\n";
    body << data.dawDiagnostics << "\n\n---\n\n";

    body << "_Report generated by " << config_.appName << " v" << config_.appVersion << "_\n";

    return body;
}
